### ISSUE TITLE
Since argument to get Odds

### ISSUE THREAD

**Issue by tiagoafonso85** [marcoblume/pinnacle.API#13] opened 2017-07-19 03:41 UTC
I've tested it in all the ways I remembered and I can not figure out the error. I think the error is in the wrapper. Otherwise, please help me solve my problem ...

I can not use since, in any function that allows it to use.
Ex:
ShowOddsDF (sportid = 29, attachLeagueInfo = TRUE, oddsformat = 'DECIMAL', islive = 1, since = x)

Where 'x' has the value of 'last', or 'x' is a variable with the value of last, obtained through the last ShowOddsDF received, without the 'since' argument.

I always get the following error:
Error in merge.data.table (., Fixtures, by.x = "leagues.events.id", by.y = "league.events.id",:
   Elements listed in `by.x` must be valid column names in x.

**Comment by shapenaji** [comment] 2017-07-19 21:59
Hi tiago,

yep, looks like a bug, 

I'll push something here shortly.

**Comment by shapenaji** [comment] 2017-07-19 22:10
So it looks like a bug in the CRAN version, it's already been fixed here in the dev version.

We'll see about getting this version over to CRAN as soon as possible.

**Comment by shapenaji** [comment] 2017-07-19 22:18
Nevermind, found the issue, since is being applied to the fixtures and the odds, and there are no new fixtures, so as a result there are no new odds. I suspect we want to split since parameter here into multiple arguments

**Comment by shapenaji** [comment] 2017-07-19 23:34
updated here, there is now another argument `fixtures_since` that controls the since parameter for the underlying fixtures.  Also, showOddsDF now only returns lines with odds (it won't return a line for every fixture), which should give a more intuitive experience when using since.

**Comment by tiagoafonso85** [comment] 2017-07-20 04:45
Hi shapenaji,

I have tried the new GitHub version and can only receive Odds of the first two / three times, using the since parameter.

Try yourself:

foo <- list()
foo[[1]] <- showOddsDF(sportid=29, attachLeagueInfo=TRUE, oddsformat='DECIMAL', islive=1)
Sys.sleep(5)
for (k in 2:6) { foo[[k]] <- showOddsDF(sportid=29, attachLeagueInfo=TRUE, oddsformat='DECIMAL', islive=1, since=foo[[k-1]]$last[1])
Sys.sleep(5) }

But if you check the value of foo[[k-1]]$last[1] in the last iteration, it has a numeric value

The error is the same:

Error in merge.data.table(., fixtures, by.x = "leagues.events.id", by.y = "league.events.id",  : 
  Elements listed in `by.x` must be valid column names in x.
In addition: Warning message:
In merge.data.table(., fixtures, by.x = "leagues.events.id", by.y = "league.events.id",  :
  You are trying to join data.tables where 'x' argument is 0 columns data.table.

You can give an example of using fixtures_since?
I could not use this too ...

**Comment by shapenaji** [comment] 2017-07-20 14:06
Hi Tiago,

The problem was that after a few runs, there would be a small gap where there were no changes.

I added error handling there, so that it will just give you a message when there are no odds for your selections and return an empty data.frame.

Per `fixtures_since`

Example follows:

```
odds <- showOddsDF(29)

# odds associated with any fixtures that have changed since:
# note: last.Fixture and last have different values, (specifically, last is much bigger)
# if you submit the value of last to the fixtures_since argument, 
# you will not get anything back.

odds <- showOddsDF(29, fixtures_since = odds$last.Fixture[1])
```

**Comment by tiagoafonso85** [comment] 2017-07-22 23:23
Hi shapenaji,

with:

odds <- showOddsDF(29)
odds <- showOddsDF(29, fixtures_since = odds$last.Fixture[1])

 I receive: 
Error in showOddsDF(29, fixtures_since = odds$last.Fixture[1]) : 
  unused argument (fixtures_since = odds$last.Fixture[1])

--------------------------------------

With this:
foo[[1]] <- showOddsDF(sportid=29)
showOddsDF(sportid=29, since=foo[[1]]$last[1])

I receive:
Error in merge.data.table(., fixtures, by.x = "leagues.events.id", by.y = "league.events.id",  : 
  Elements listed in `by.y` must be valid column names in y.
In addition: Warning message:
In merge.data.table(., fixtures, by.x = "leagues.events.id", by.y = "league.events.id",  :
  You are trying to join data.tables where 'y' argument is 0 columns data.table.


What message should I expect to receive when no odds are available and return an empty date.frame? I still get the same error...

It would be easier, if when there are no odds available, showOddsDF returns some kind of result, not to result in an error, which I can not resolve ...

Sorry, I did not realize yet shapenaji

**Comment by shapenaji** [comment] 2017-07-23 14:07
Hi tiago, are you still on the old version? I can't reproduce those errors on the current version here on github.

```devtools::install_github('marcoblume/pinnacle.API')```

**Comment by tiagoafonso85** [comment] 2017-07-23 18:09
Yes, you are right. I was in CRAN version with,
Install.packages ('pinnacle.api')

My mistake.

Thank you, it works =)

**Comment by shapenaji** [comment] 2017-07-23 18:21
Excellent, I'll close this then.

**Closed as completed by shapenaji** 2017-07-23 18:21 UTC
Labels: bug
